### ISSUE TITLE
/deep/ doesn't compile exactly like >>>

### ISSUE THREAD

**Issue by mathieutu** [vuejs/vue-loader#1035]
### Version
13.3.0

### Steps to reproduce
```html
<style scoped>
    >>> .foo {
        font-weight: bold;
    }
</style>
```
is compiled to:
```css
[data-v-5026efab] .foo {
font-weight: bold;
}
```

**BUT**

```html
<style scoped>
    /deep/ .foo {
        font-weight: bold;
    }
</style>
```
is compiled to:
```css
[data-v-5026efab].foo {
font-weight: bold;
}
```

### What is expected?
Exact same compilation.

### What is actually happening?
Note the removed space during the `/deep/` compilation.

---
For me, it comes from theses lines:
https://github.com/vuejs/vue-loader/blob/5673319d78342e530a8ef799f1088770a87f92a9/lib/style-compiler/plugins/scope-id.js#L33-L35

I don't understand why we should remove the space after just in this case. If it's done on purpose this should be documented:

>https://vue-loader.vuejs.org/en/features/scoped-css.html
>In those cases you can use the /deep/ combinator instead - it's an alias for >>> and **works exactly the same**.

I can make a PR if you want.
