### ISSUE TITLE
Missing negation selector in css when transpiling from scss

### ISSUE THREAD

**Issue by Eseperio** [vuejs/vue-loader#1939]
The following css rule

```scss
.menu-column {
    .background {
        & ~ /deep/ {
               div:not(.block .modal) {
                   .btn {
                         border:10px solid green;
                         box-shadow: 0px 0px 4px black;
              }
        }
      }
    }
}

```

Should generate :
```
.menu-column .background[data-v-8236573c] ~ div:not(.block .modal) .btn {}
```

Generates this instead:
```
.menu-column .background[data-v-8236573c] ~ div .btn {}
```

`:not` is being ignored.
