### ISSUE TITLE
Missing negation selector in css when transpiling from scss #1939

### ISSUE THREAD

**Issue by Eseperio** [vuejs/vue-loader#1940]
### Version
16.8.3

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/serene-volhard-f0ux0u?file=/src/App.vue:0-994)

### Steps to reproduce
Write this code as scss in a SFC

```css
.menu-column {
    .background {
        & ~ /deep/ {
               div:not(.block .modal) {
                   .btn {
                         border:10px solid green;
                         box-shadow: 0px 0px 4px black;
              }
        }
      }
    }
}
```

### What is expected?
.menu-column .background[data-v-8236573c] ~ div:not(.block .modal) .btn {}

### What is actually happening?
.menu-column .background[data-v-8236573c] ~ div .btn {}

---
:not pseudo selector is missing

IMPORTANT: It looks like neither codesandbox nor sfc playground support selector or scss. So provided example will not work. You must compile locally.
