### ISSUE TITLE
Attribute in the scoped stylesheet added to the last selector in a chain

### ISSUE THREAD

**Issue by adambabik** [vuejs/vue-loader#394]
Hi,

I played with scoped stylesheets today and I noticed something strange in my opinion. Let's look at the example:
```scss
<style scoped lang="scss">
.chart rect {
  fill: red;
}
</style>
```
It produces:
```css
.chart rect[data-v-1] {
  fill: red;
}
```
Why is `id` appended to the last selector in a chain instead of the first one? Is it a bug or expected behavior? 

It would be much more useful to append the `id` to the first selector as this way it's possible to style e.g. HTML elements rendered with other libraries inside a component. It's probably less efficient, but using attributes is not really efficient in the first place, so I guess it's not a case.

Thanks!
