### ISSUE TITLE
Use transition in css modules

### ISSUE THREAD

**Issue by banricho** [vuejs/vue-loader#494]
class name in css modules will be compiled to `[name]-[hash]`, but when use transition, it should be `[name]-enter-[hash]`.

```HTML
<transiton :name="$style.demo">
</transiton>
```

`$style.demo` is not compiled, and class name in `.css` file is compiled to `demo-enter-xxxx`.

**Comment by LinusBorg** [comment]
This is not a bug - CSS modules in vue-loader just don't support that currently.

**Comment by yyx990803** [comment]
Instead of `name`, you can also directly use `enter-class/leave-class` props to directly specify class names instead of relying on auto-inferring.

**Comment by johnsoncodehk** [comment]
You can use css module selector ```:global``` with scss, for example:
```vue
<style module lang="scss">
.demo {
  &:global(-enter-active) { /* ... */ }
  &:global(-leave-active) { /* ... */ }
  &:global(-enter) { /* ... */ }
  &:global(-leave-to) { /* ... */ }
}
</style>
```

**Comment by sombriks** [comment]
this is a nice improvement. would be nice to see it happen.

**Comment by amirmeimari** [comment]
No update on this issue?

**Comment by adamreisnz** [comment]
@amirmeimari , as per @yyx990803's comment above, you can just use:

```html
<Transition
  :enter-active-class="$style.transitionStart"
  :leave-active-class="$style.transitionStart"
  :enter-from-class="$style.transitionEnd"   :leave-to-class="$style.transitionEnd"   appear
>...</Transition>
```

And then:

```css
<style module lang="scss">
.transitionStart {
  transition: all .1s cubic-bezier(0.25, 0.25, 0.75, 0.75) 0s;
}
.transitionEnd {
  transform: translateX(5px) translateY(-5px);
  opacity: 0;
}
</style>
```

Just note that in Vue 2, the `enter-from-class` prop doesn't work and you need to use `enter-class` instead.
