### ISSUE TITLE
Scoped CSS incorrectly generates selector with global descendant

### ISSUE THREAD

**Issue by mfro** [vuejs/vue-loader#513]
Take the following styles in a vue component:
    
    <style module>
    .parent :global(.child) {
        color: blue;
    }
    </style>
    
    <style scoped>
    .parent :global(.child) {
        background: red;
    }
    </style>

This generated the following css:
    
    ._36lBVnT0bRLIWG0CZzp9gL_0 .child {
        color: blue;
    }
    
    .parent [data-v-d247dcf4].child {
        background: red;
    }
This is incorrect generation. The `module` css is correct but the `scoped` css is incorrect.

The child has blue text but has no red background:

    <div class="_36lBVnT0bRLIWG0CZzp9gL_0 parent" data-v-d247dcf4>
        <div class="child">Test</div>
    </div>
The scoped css does match this (but should not):

    <div class="_36lBVnT0bRLIWG0CZzp9gL_0 parent">
        <div class="child" data-v-d247dcf4>Test</div>
    </div>

**Comment by LinusBorg** [comment]
Could you also provide the template you used for this?

**Comment by mfro** [comment]
Here a full component that highlights the issue:
    
    <template>
        <div :class="$style.parent"></div>
    </template>
    
    <script>
        export default {
            mounted() {
                var child = document.createElement('div');
                child.className = 'child';
                child.innerText = 'TEST';
                this.$el.appendChild(child);
            }
        }
    </script>
    
    <style module>
    .parent :global(.child) {
        color: blue;
    }
    </style>
    
    <style scoped>
    .parent :global(.child) {
        background: red;
    }
    </style>

**Comment by mercs600** [comment]
I got the same problem with scoped css 
```html
<style scoped>
header :global(.icon) {
      opacity: 0.6;
    }
</style>
```

should generate selector like: 

```html
header[data-v-0edbec5a] .icon 
```

I got 
```html
header [data-v-0edbec5a].icon {
```

**Comment by Jinjiang** [comment]
The syntax `:global(...)` is just from CSS Modules. So it won't work in scoped CSS. I suggest using deep selectors like `.a >>> .b { /* ... */ }`.

* `header :global(.icon) { ... }` -> `header >>> .icon { ... }`
*  `.parent :global(.child) { ... }` -> `.parent >>> .child { ... }`

Thanks.

**Comment by mercs600** [comment]
@Jinjiang I did see it... I was trying to use it, but the result after compile is: 
```css
header >>> .icon[data-v-0edbec5a] {
  opacity: 1;
}
```

or with scss

```css
header /deep/ .icon[data-v-0edbec5a] {
  opacity: 1;
}
```

Any suggest ? I don't know if it is vue-loader problem or some styles loader

**Comment by Jinjiang** [comment]
I use the latest [webpack](https://github.com/vuejs-templates/webpack) template and change `App.vue` into:

``` vue
<template>
  ...
</template>

<style>
.parent .child {
  color: white;
}
.parent :global(.child) {
  color: white;
}
</style>

<style module>
.parent .child {
  color: green;
}
.parent :global(.child) {
  color: green;
}
</style>

<style scoped>
.parent .child {
  color: blue;
}
.parent :global(.child) {
  color: blue;
}
.parent >>> .child {
  color: red;
}
</style>

<style scoped lang="scss">
.parent .child {
  color: yello;
}
.parent :global(.child) {
  color: yello;
}
.parent /deep/ .child {
  color: black;
}
</style>
```

The generated `<style>` elements are:

``` css
.parent .child {
  color: white;
}
.parent .child {
  color: white;
}

/* ---- */

.pHjbraxRO-A0qwMT0VLWS_1 ._2XfSgG3Mr5wsr_fBf8O0WO_1 {
  color: green;
}
.pHjbraxRO-A0qwMT0VLWS_1 .child {
  color: green;
}

/* ---- */

.parent .child[data-v-7ba5bd90] {
  color: blue;
}
.parent[data-v-7ba5bd90] .child {
  color: blue;
}
.parent[data-v-7ba5bd90] .child {
  color: red;
}

/* ---- */

.parent .child[data-v-7ba5bd90] {
  color: yello;
}
.parent[data-v-7ba5bd90] .child {
  color: yello;
}
.parent[data-v-7ba5bd90] .child {
  color: black;
}
```

If you get the different result, please show your simplest demo and of course with the whole env & config to reproduce it.

Thanks.
