### ISSUE TITLE
使用postcss-cssnext处理csss属性前缀的问题

### ISSUE THREAD

**Issue by jinjl** [vuejs/vue-loader#930]
在组件中如果样式是添加了scoped,并且样式定义了@keyframes，经过cssnext处理后的keyframes name中不一致。具体如下：

``` css
@-webkit-keyframes bounceInDown {
	0%,60%,75%,90%,to {
		-webkit-animation-timing-function: cubic-bezier(.215,.61,.355,1);
		animation-timing-function: cubic-bezier(.215,.61,.355,1)
	}

	0% {
		opacity: 0;
		-webkit-transform: translate3d(0,-3000px,0);
		transform: translate3d(0,-3000px,0)
	}

	60% {
		opacity: 1;
		-webkit-transform: translate3d(0,25px,0);
		transform: translate3d(0,25px,0)
	}

	75% {
		-webkit-transform: translate3d(0,-10px,0);
		transform: translate3d(0,-10px,0)
	}

	90% {
		-webkit-transform: translate3d(0,5px,0);
		transform: translate3d(0,5px,0)
	}

	to {
		-webkit-transform: none;
		transform: none
	}
}

@keyframes bounceInDown-data-v-599762d2 {
	0%,60%,75%,90%,to {
		-webkit-animation-timing-function: cubic-bezier(.215,.61,.355,1);
		animation-timing-function: cubic-bezier(.215,.61,.355,1)
	}

	0% {
		opacity: 0;
		-webkit-transform: translate3d(0,-3000px,0);
		transform: translate3d(0,-3000px,0)
	}

	60% {
		opacity: 1;
		-webkit-transform: translate3d(0,25px,0);
		transform: translate3d(0,25px,0)
	}

	75% {
		-webkit-transform: translate3d(0,-10px,0);
		transform: translate3d(0,-10px,0)
	}

	90% {
		-webkit-transform: translate3d(0,5px,0);
		transform: translate3d(0,5px,0)
	}

	to {
		-webkit-transform: none;
		transform: none
	}
}
```

一个keyframe 为bounceInDown-data-v-599762d2，cssnext生成的为bounceInDown。
